name: CI with Maven and Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
 #   - name: Build with Maven
 #     run: mvn -B package --file pom.xml
 
    - name: Build
      run: mvn --batch-mode -DskipTests package
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Test
     # run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      run: mvn --batch-mode test

    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
        
    #- name: generating code coverage xml report
    #  run: mvn cobertura:cobertura
      
    - name: download uploader for code Coverage
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      
    - name: change permission  
      run: chmod +x codecov
      
    - name: run codecov
      run: ./codecov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
